## Random value generatior in numpy 

In [1]:
import numpy as np 

# Create a random number generator 

In [6]:

# Creates NumPy's modern random-number generator.
rng = np.random.default_rng()

# Creates a reproducible generator.
# The same seed produces the same random results.
rng = np.random.default_rng(seed=42)



## Generate random values (float)

In [7]:

# ============================================================
# BASIC RANDOM VALUES
# ============================================================

# Generates one random float between 0.0 and 1.0.
random_number = rng.random()
print(random_number)


# Generates an array of random floats between 0.0 and 1.0.
random_array = rng.random(size=5)
print(random_array)


# Generates a 2 × 3 array of random floats.
random_matrix = rng.random(size=(2, 3))
print(random_matrix)

0.7739560485559633
[0.43887844 0.85859792 0.69736803 0.09417735 0.97562235]
[[0.7611397  0.78606431 0.12811363]
 [0.45038594 0.37079802 0.92676499]]


## Generate Random Integer 

In [8]:



# ============================================================
# RANDOM INTEGERS
# ============================================================

# Generates one random integer from 0 to 9.
# The upper limit 10 is excluded.
number = rng.integers(low=0, high=10)
print(number)


# Generates five random integers from 1 to 100.
numbers = rng.integers(low=1, high=101, size=5)
print(numbers)


# Includes the upper limit when endpoint=True.
number = rng.integers(low=1, high=10, endpoint=True)
print(number)



7
[65 41 83 55 45]
5


## Selecte random choice 

In [10]:

# ============================================================
# RNG.CHOICE()
# ============================================================

# Selects one random item from an array or list.
fruits = np.array(["apple", "banana", "mango", "orange"])

selected_fruit = rng.choice(fruits)
print(selected_fruit)


# Selects three items.
# Repeated items are allowed by default.
selected_fruits = rng.choice(fruits, size=3)
print(selected_fruits)


# Selects three unique items.
# replace=False means an item cannot be selected twice.
selected_fruits = rng.choice(fruits, size=3, replace=False)
print(selected_fruits)


# Selects items using custom probabilities.
# The probabilities must add up to 1.
selected_fruits = rng.choice(
    fruits,
    size=5,
    p=[0.1, 0.2, 0.6, 0.1]
)

print(selected_fruits)


# Selects random numbers from 0 to 9.
selected_numbers = rng.choice(10, size=4)
print(selected_numbers)


apple
['apple' 'mango' 'orange']
['orange' 'mango' 'apple']
['mango' 'mango' 'orange' 'mango' 'mango']
[7 1 3 4]


## Shuffle 

In [12]:


# ============================================================
# RNG.SHUFFLE()
# ============================================================

# Randomly changes the order of an array in place.
# The original array is modified.
numbers = np.array([1, 2, 3, 4, 5])

rng.shuffle(numbers)

print(numbers)


[4 3 1 5 2]


In [ ]:


# ============================================================
# RNG.PERMUTATION()
# ============================================================

# Returns a shuffled copy without changing the original array.
numbers = np.array([1, 2, 3, 4, 5])

shuffled_copy = rng.permutation(numbers)

print("Original:", numbers)
print("Shuffled:", shuffled_copy)


# ============================================================
# RNG.UNIFORM()
# ============================================================

# Generates random floats from a uniform distribution.
# Every value between low and high has an equal chance.
uniform_numbers = rng.uniform(low=10, high=20, size=5)

print(uniform_numbers)


# ============================================================
# RNG.NORMAL()
# ============================================================

# Generates values from a normal or Gaussian distribution.
# loc = mean
# scale = standard deviation
normal_numbers = rng.normal(loc=0, scale=1, size=5)

print(normal_numbers)


# Generates normally distributed exam scores.
# Mean score = 70
# Standard deviation = 10
exam_scores = rng.normal(loc=70, scale=10, size=10)

print(exam_scores)


# ============================================================
# RNG.STANDARD_NORMAL()
# ============================================================

# Generates values from the standard normal distribution.
# Mean = 0 and standard deviation = 1.
standard_normal = rng.standard_normal(size=5)

print(standard_normal)


# ============================================================
# RNG.BINOMIAL()
# ============================================================

# Simulates the number of successes in repeated trials.
# n = number of trials
# p = probability of success
# size = number of experiments
coin_toss_results = rng.binomial(n=10, p=0.5, size=5)

print(coin_toss_results)


# Example:
# Simulate how many students pass out of 100 students.
# Each student has an 80% probability of passing.
passed_students = rng.binomial(n=100, p=0.8)

print(passed_students)


# ============================================================
# RNG.POISSON()
# ============================================================

# Generates event counts from a Poisson distribution.
# lam is the expected average number of events.
customer_arrivals = rng.poisson(lam=5, size=10)

print(customer_arrivals)


# Example:
# Average number of website visitors per minute is 20.
visitors_per_minute = rng.poisson(lam=20, size=5)

print(visitors_per_minute)


# ============================================================
# RNG.EXPONENTIAL()
# ============================================================

# Generates waiting-time values from an exponential distribution.
# scale represents the average waiting time.
waiting_times = rng.exponential(scale=5, size=10)

print(waiting_times)


# ============================================================
# RNG.BETA()
# ============================================================

# Generates values between 0 and 1 from a beta distribution.
# Commonly used for probabilities and proportions.
probabilities = rng.beta(a=2, b=5, size=10)

print(probabilities)


# ============================================================
# RNG.MULTINOMIAL()
# ============================================================

# Simulates counts across multiple categories.
# n = total number of trials
# pvals = probability of each category
dice_results = rng.multinomial(
    n=100,
    pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
)

print(dice_results)


# ============================================================
# RNG.RANDOM VS RNG.INTEGERS
# ============================================================

# rng.random() produces decimal numbers from 0.0 to 1.0.
decimal_values = rng.random(size=5)

# rng.integers() produces integer values within a specified range.
integer_values = rng.integers(0, 10, size=5)

print("Decimals:", decimal_values)
print("Integers:", integer_values)


# ============================================================
# NP.CLIP() — NOT RNG.CLIP()
# ============================================================

# Limits array values to a specified minimum and maximum.
# Values below 0 become 0.
# Values above 10 become 10.
values = np.array([-5, 2, 7, 15, 20])

clipped_values = np.clip(values, 0, 10)

print(clipped_values)


# The same operation can be called directly from an array.
clipped_values = values.clip(0, 10)

print(clipped_values)


# ============================================================
# THERE IS NO RNG.IO()
# ============================================================

# This is invalid:
# rng.io()

# You may have meant rng.integers():
result = rng.integers(0, 10, size=5)

print(result)


# ============================================================
# VIEW AVAILABLE RNG METHODS
# ============================================================

# Displays all public methods and attributes available in rng.
available_methods = [
    name for name in dir(rng)
    if not name.startswith("_")
]

print(available_methods)